### ISSUE TITLE
strings  recognize error

### ISSUE THREAD

**Issue by Fangfang6606** [bthornton191/adams_vscode#3]
hi ，this strings seems to be recognized as a variable
![屏幕截图 2023-11-30 101414](https://github.com/bthornton191/adams_vscode/assets/65446486/ced43a83-44e9-4a90-992f-c2a95a099c33)

**Comment by bthornton191** [comment]
A fix has been implemented in v0.4.6 (currently in pre-release).

@Fangfang6606, I've tested it on my end, but if you have time it would be great if you could give it a shot too and let me know if you see any issues.
